apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*laravel*.log
      pos_file /var/log/fluentd-containers-laravel.log.pos
      tag kubernetes.laravel.*
      <parse>
        @type none
        format none
        multiline_flush_interval 5s
      </parse>
      read_from_head true
    </source>
    
    <filter kubernetes.laravel.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.laravel.**>
      @type record_transformer
      remove_keys $.docker.container_id, $.kubernetes.container_image, $.kubernetes.container_image_id, $.kubernetes.container_name, $.kubernetes.host, $.kubernetes.labels.app, $.kubernetes.labels.pod-template-hash, $.kubernetes.master_url, $.kubernetes.namespace_id, $.kubernetes.namespace_labels.kubernetes_io/metadata_name, $.kubernetes.namespace_name, $.kubernetes.pod_id, $.kubernetes.pod_ip, $.kubernetes.pod_name.keyword, $.message.keyword, $.tag.keyword
    </filter>

    <match kubernetes.laravel.**>
      @type elasticsearch
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME']}"
      reload_connections true
      logstash_format true
      logstash_prefix aws.stage.laravel.pods
      <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.laravel.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 5s
          retry_forever true
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 32
          overflow_action block
       </buffer>
    </match>
